# Generated by Django 4.0 on 2021-12-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
