# Generated by Django 4.0 on 2021-12-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phon_number',
            new_name='phone_number',
        ),
    ]
