# Generated by Django 4.0 on 2021-12-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phon_number_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_site',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
