# Generated by Django 4.0 on 2021-12-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_personal_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_site',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
